### ISSUE TITLE
More detailed errors for updater

### ISSUE THREAD

**Issue by DesertDogSledder** [DesertDogSledder/wca#9]
Report more detailed errors for the updater to assist in troubleshooting

**Comment by darrylmasson** [comment]
For making system calls from python, I typically use `subprocess.Popen` rather than `subprocess.call` as it's trivially easy to capture stderr and stdout. This might make it simpler to see what git complains about

**Comment by DesertDogSledder** [comment]
@darrylmasson Thank you so much for the suggestion!  I'll try that out.
